[package]
name = "wachy"
version = "0.1.0"
authors = ["Vivek Jain <vivek.jain@rubrik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = { path = "../addr2line" }
backtrace = "0.3.50"
cplus_demangle = "0.1.1"
cursive = "0.15.0"
cursive_table_view = { path = "../cursive_table_view" }
fuzzy-matcher = "0.3.5"
gimli = "0.22"
itertools = "0.9.0"
libc = "0.2.77"
log = "0.4.11"
memmap = "0.7.0"
object = "0.20"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
simple-logging = "2.0.2"
zydis = "3.1.1"
