[package]
name = "wachy"
version = "0.1.0"
authors = ["Vivek Jain <vivek.jain@rubrik.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = { path = "../addr2line" }
cplus_demangle = { path = "../cplus_demangle" }
cursive = "0.15.0"
env_logger = "0.7.1"
fuzzy-matcher = "0.3.5"
gimli = { path = "../gimli" }
log = "0.4.11"
memmap = "0.7.0"
object = "0.21.1"
